Repository DO-SOPT-SOPKATHON/Team1-Server, pull requests merged in 2023-11, with the labels that each got.

#1 feat: Review, BaseEntity 추가
  src/main/java/sopkathon/team1/common/config/SwaggerConfig.java
  src/main/java/sopkathon/team1/domain/BaseEntity.java
  src/main/java/sopkathon/team1/domain/review/Review.java
Labels: 혜연, feat

#2 [feat] Category, Post 엔티티 생성
  src/main/java/sopkathon/team1/domain/BaseEntity.java
  src/main/java/sopkathon/team1/domain/category/Category.java
  src/main/java/sopkathon/team1/domain/category/CategoryType.java
  src/main/java/sopkathon/team1/domain/post/Post.java
  src/main/java/sopkathon/team1/domain/review/Review.java
Labels: 희정, feat

#3 [fix] posts 타입오류 수정
  src/main/java/sopkathon/team1/domain/category/Category.java
Labels: 희정, fix

#4 [feat] Review 생성 기능 구현
  src/main/java/sopkathon/team1/controller/ReviewController.java
  src/main/java/sopkathon/team1/domain/category/Category.java
  src/main/java/sopkathon/team1/domain/category/CategoryType.java
  src/main/java/sopkathon/team1/dto/request/ReviewRequest.java
  src/main/java/sopkathon/team1/repository/PostRepository.java
  src/main/java/sopkathon/team1/repository/ReviewRepository.java
  src/main/java/sopkathon/team1/service/ReviewService.java
Labels: 희정, feat

#5 Feat/hyeyeon/#3
  src/main/java/sopkathon/team1/controller/PostController.java
  src/main/java/sopkathon/team1/domain/category/Category.java
  src/main/java/sopkathon/team1/domain/post/Post.java
  src/main/java/sopkathon/team1/dto/request/PostCreateRequest.java
  src/main/java/sopkathon/team1/dto/response/PostCreateResponse.java
  src/main/java/sopkathon/team1/repository/CategoryRepository.java
  src/main/java/sopkathon/team1/repository/PostRepository.java
  src/main/java/sopkathon/team1/service/PostService.java
  src/main/resources/application.properties
  src/main/resources/data.sql
Labels: 혜연, feat

#6 [feat] 일기 단건 조회 기능 구현
  src/main/java/sopkathon/team1/controller/PostController.java
  src/main/java/sopkathon/team1/controller/ReviewController.java
  src/main/java/sopkathon/team1/domain/BaseEntity.java
  src/main/java/sopkathon/team1/domain/post/Post.java
  src/main/java/sopkathon/team1/domain/review/Review.java
  src/main/java/sopkathon/team1/dto/response/PostResponse.java
  src/main/java/sopkathon/team1/dto/response/ReviewResponse.java
  src/main/java/sopkathon/team1/repository/ReviewRepository.java
  src/main/java/sopkathon/team1/service/PostService.java
  src/main/java/sopkathon/team1/service/ReviewService.java
Labels: 희정, feat

#7 [feat] 일기 랜덤 조회 기능 구현
  src/main/java/sopkathon/team1/controller/PostController.java
  src/main/java/sopkathon/team1/service/PostService.java
Labels: 희정, feat

#8 [feat] 카테고리별 다이어리 조회 기능 구현
  src/main/java/sopkathon/team1/controller/PostController.java
  src/main/java/sopkathon/team1/dto/response/PostGetResponse.java
  src/main/java/sopkathon/team1/exception/BusinessException.java
  src/main/java/sopkathon/team1/exception/CategoryException.java
  src/main/java/sopkathon/team1/exception/CommonErrorCode.java
  src/main/java/sopkathon/team1/exception/CustomErrorCode.java
  src/main/java/sopkathon/team1/exception/ResultCode.java
  src/main/java/sopkathon/team1/exception/ResultResponse.java
  src/main/java/sopkathon/team1/repository/CategoryRepository.java
  src/main/java/sopkathon/team1/repository/PostRepository.java
  src/main/java/sopkathon/team1/service/PostService.java
Labels: 혜연, feat
